### PR TITLE
Feature/5languages extension

### PR DESCRIPTION
**Pull request by vuphan-adnovumvn**

### CODE REVIEW

**Comment by mrolli** [comment]
On behalf of @stemind:

The file u5admin/filesa.php iframed by its top parent u5admin/uploada.php is still 3 languages instead of 5.

This file can be seen in action under https://nemulbnesraam.ch/V12/u5admin/uploada.php?name=album&typ=a

what means

1. go to https://nemulbnesraam.ch/V12/u5admin/
2. Log in with 
     Temp 
     FirstPassword7
3. Go to the radio button I in the PIDVESA radio button series in the upper right corner
4. If necessary switch to std Images (toggle link free Images<->std Images
5. There you see the object named album, click on the U link to open https://nemulbnesraam.ch/V12/u5admin/uploada.php?name=album&typ=a

BTW: Such album objects can be produces according to page 17 in the manual https://yuba.ch/r/u5cmsmanualenglisch/u5cmsmanualenglisch_en.pdf

**Comment by vuphan-adnovumvn** [comment]
> On behalf of @stemind:
> 
> The file u5admin/filesa.php iframed by its top parent u5admin/uploada.php is still 3 languages instead of 5.
> 
> This file can be seen in action under https://nemulbnesraam.ch/V12/u5admin/uploada.php?name=album&typ=a
> 
> what means
> 
>     1. go to https://nemulbnesraam.ch/V12/u5admin/
> 
>     2. Log in with
>        Temp
>        FirstPassword7
> 
>     3. Go to the radio button I in the PIDVESA radio button series in the upper right corner
> 
>     4. If necessary switch to std Images (toggle link free Images<->std Images
> 
>     5. There you see the object named album, click on the U link to open https://nemulbnesraam.ch/V12/u5admin/uploada.php?name=album&typ=a
> 
> 
> BTW: Such album objects can be produces according to page 17 in the manual https://yuba.ch/r/u5cmsmanualenglisch/u5cmsmanualenglisch_en.pdf

Hi @mrolli 
I've fixed the problem at commit 91f92ff6cb7d45d63b4e6ea057cf768fa683bf00 
Please review again.
Thanks 
Vu

**Review by stemind — CHANGES_REQUESTED** [review]
https://nemulbnesraam.ch/V12/u5admin/titlefixum.php is a form with action target https://nemulbnesraam.ch/V12/u5admin/titlefixum2.php which updates the database.

titlefixum2.php got forgotten what the language extension is concerned.

**Review by stemind — CHANGES_REQUESTED** [review]
When the 5th language is removed (empty the 5th fields "two letter language code" and "name of the language" in https://nemulbnesraam.ch/V12/u5admin/definelanguages.php), the rendering of the language links does no longer white-spacing between the language links:
nok
ok

**Review by stemind — CHANGES_REQUESTED** [review]
Here a tiny optimization in u5admin/upload.php

Rise iframe height from 110 to 180

Thanks!

**Comment by stemind** [comment]
Whereas importing u5standard.sql works well, importing u5congress.sql throws an error (see attachment).
dbdumpnok

**Comment by vuphan-adnovumvn** [comment]
> Whereas importing u5standard.sql works well, importing u5congress.sql throws an error (see attachment). dbdumpnok

Hi @stemind 
Do you mean u5conference.sql?

**Review by mrolli — APPROVED** [review]
Thank you for your enormous good work, highly appreciated. Greetings from Switzerland.

**Comment by mrolli** [comment]
@vuphan-adnovumvn We encountered an issue during the first migration of an existing instance. Your take on the /r/runonce.php is not compatible with mariadb-10.3.x (we run on 10.3.35), which is still common in the wild. Your usage of RENAME COLUMN is only compatible with mariadb-10.5.2+. 

We know that we did not specify the minimum version for compatibility, still we'd appreciate if you would change the SQL statement in order to safely run on mariadb-10.3.35. Please keep in mind that when using CHANGE COLUMN you'll also have to specify the column type and the default, which shall be preserved as it is.

**Pull request merged**
